[package]
name = "liquid-rust"
version = "0.1.0"
authors = ["Nico Lehmann <nico.lehmannm@gmail.com>"]
edition = "2018"
exclude = ["old/**/*"]

[dependencies]
regex = "1.4"
lalrpop-util = "0.19"
if_chain = "1.0"
rsmt2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[[bin]]
name = "lr"
path = "src/cps_ref/main.rs"

[build-dependencies.lalrpop]
version = "0.19"
features = ["lexer"]
