[package]
name = "liquid-rust"
version = "0.1.0"
authors = ["Nico Lehmann <nico.lehmannm@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
lalrpop-util = "0.19.0"
if_chain = "1"
rsmt2 = "0.10.0"
serde = "1"
serde_json = "1"

[build-dependencies.lalrpop]
version = "0.19.0"
features = ["lexer"]
