[workspace]
members = [
  "liquid-rust",
  "liquid-rust-common",
  "liquid-rust-core",
  "liquid-rust-core-cli",
  "liquid-rust-driver",
  "liquid-rust-liquid",
  "liquid-rust-parser",
  "liquid-rust-typeck",
]
