[package]
name = "liquid-rust-driver"
version = "0.1.0"
authors = ["Nico Lehmann <nico.lehmannm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
liquid-rust-core = { path = "../liquid-rust-core" }
liquid-rust-typeck = { path = "../liquid-rust-typeck" }
