[package]
name = "liquid-rust-core"
version = "0.1.0"
authors = ["Nico Lehmann <nico.lehmannm@gmail.com>"]
edition = "2018"

[dependencies]
liquid-rust-common = { path = "../liquid-rust-common" }
quickscope = "0.1"
hashconsing = "1.2"
indexmap = "1.6"
