name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Cache toolchain
        uses: actions/cache@v1
        with:
          path: /usr/share/rust/.rustup
          key: toolchain-${{ hashFiles('rust-toolchain') }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustc-dev

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
